---
- name: Install Pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_user_dir }}/.pyenv"
    update: yes
  tags: [python]

- name: Install Pyenv Virtualenv Plugin
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ ansible_user_dir }}/.pyenv/plugins/pyenv-virtualenv"
    update: yes
  tags: [python]