---
- name: Ensure Local Bin Directory
  file:
    path: "{{ ansible_user_dir }}/.local/bin"
    state: directory
    mode: '0755'
  tags: [scripts]

- name: Download User Scripts
  get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item.name }}"
    mode: '0755'
  loop: "{{ executable_scripts }}"
  tags: [scripts]